###################
### VARIABLES ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/
$MEH = ALT SHIFT CTRL           # sets the "MEH" key
$HYPER = SUPER ALT SHIFT CTRL   # sets the "HYPER" key

# set programs
$browser = waterfox
$fileManager = dolphin
$menu = rofi -show drun
$terminal = ghostty

